version: '3.7'

services:
  # WordPress service
  wordpress:
    image: wordpress:latest
    container_name: Wordpress-container
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: nayab
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - wp_network
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html

  # MySQL database service
  db:
    image: mysql:latest
    container_name: cont-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: nayab
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ports:
       - "8081:80"
    networks:
      - wp_network
    volumes:
      - ./db_data:/var/lib/mysql
networks:
  wp_network:
    driver: bridge
